### ISSUE TITLE
[Feature] Suppress the program specified by user

### ISSUE THREAD

**Issue by zzeitt** [pit-ray/win-vind#100]
**Suppress `win-vind` for the program specified by user**
Hi @pit-ray, I am addicted to `win-vind` ever since I've used this tool.

In my daily work, I use MS Edge Browser with plugin `Vimium` frequently.

However, it's annoying that I have to switch to 'RESIDENT MODE' manually every time I open an Edge window.

I noticed that there is a **suppress_for_vim** function built in this tool.

My question is can we implement a function to make `win-vind` suppress for the program specified by user?
Like `set suppress_program=msedge.exe`.

**Related projects (Optional)**
Here I found the source code of **suppress_for_vim**:
https://github.com/pit-ray/win-vind/blob/2d7c1cda120eef31083ba689e94e855eb31f9bf3/src/opt/suppress_for_vim.cpp#L49
Maybe we could use a variable to replace the constant string 'vim' during string matching.

**Comment by pit-ray** [comment]
As mentioned in #89, we must solve this problem.

The plan is to determine this based on the **executable name** or **path** (relative or absolute) with a notation similar to `arrangewin_ignore` option in  `arrange_windows`.

https://github.com/pit-ray/win-vind/blob/2d7c1cda120eef31083ba689e94e855eb31f9bf3/src/bind/window/arrange_win.cpp#L193-L203
If possible, please send a pull request.
I will accept any discussions and questions for implementation in the pull request thread, so please feel free to do so.
Otherwise, I would like to implement this as v4.5.

Thanks for your contribution.

**Comment by zzeitt** [comment]
Oh, sorry for missing the previous issue. I will subscribe this #89..

The feature seems to be feasible since there already has a config **arrangewin_ignore** running fine. I am still busy in recent days, so maybe I could attempt to modify the source code when I am get more spare time.

Thanks for your great job.

**Comment by pit-ray** [comment]
Since there seems to be a lot of requests, I will implement this as a priority.
Thanks.

**Comment by zzeitt** [comment]
Great to hear that! Can't wait to see the new feature. 
Thank you for your hard effort.
