### ISSUE TITLE
[Feature] Add latest version on the Downloads page

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#116]
Hi,

This is the page:
https://pit-ray.github.io/win-vind/downloads/

It is a minor thing but will be useful to track the latest version. Right now the version is only given in the installer file name, but that requires to actually download the file in order to find out the version.

Having it displays on this page (and others?) would make it is easy to follow up on what's new.

Thanks for considering.

**Comment by pit-ray** [comment]
I see.

If you can, please pull requests. Of course, I give any information to help the contributions.
Otherwise, I'll fix it later.

Thanks for your contributions.

P.S.
The documents are deployed in the [docs](https://github.com/pit-ray/win-vind/tree/master/docs) directory, and it is based on [Jekyll Docs Theme](https://github.com/allejo/jekyll-docs-theme) and [Bootstrap](https://getbootstrap.com/docs/5.2/getting-started/introduction/). The version information is shown on the top page, so it maybe helps you.

**Comment by gilbh** [comment]
Thanks!

I never did a PR (not fork for that matter). Also, I wouldn't know how to add the dynamic value of version to the page.

Sorry I can't be of much help on this front, I am code in Python as a hobby ...

**Comment by pit-ray** [comment]
Understood.
Then, I'll add it after done pull requests for autocmd and the new mapping system.

Thanks again.

**Comment by pit-ray** [comment]
I added a brief notation for now.

**Comment by gilbh** [comment]
Yeah, I just saw it. Thanks!
