### ISSUE TITLE
[Bug] Current version is not showing in beta releases

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#137]
I think we discussed this before, but now as I am testing v5.0.2 vs. v5.0.3 it is crucial to be able to differentiate between the version. Right now, both show this:
![image](https://user-images.githubusercontent.com/39532610/211810952-ddcd11bb-1f82-405e-a4e4-77caa0ca90ef.png)

-- which makes it difficult to figure out what is the current version ...

Let me know what you think.

Thanks!

**Comment by pit-ray** [comment]
This is not a bug.

As I mentioned before, the About popup shows for only the production release, not for the beta version. Because I don't plan to take the beta version to the store (chocolatey or winget), so I thought the showing for the beta version is redundant.

However, the differentiability between the production release and beta is needed, so I'll add a fourth version and treat it as an implicit TAG version. But, the top three will continue to handle as MAJOR.MINOR.PATCH as before.

- Conventional version format
```
MAJOR.MINOR.PATCH
```
- New version format
```
MAJOR.MINOR.PATCH.TAG
```

Thanks.

**Comment by pit-ray** [comment]
I released the beta4 including this change, please try it.
https://github.com/pit-ray/win-vind/releases/tag/v5.0.0-beta4
