### ISSUE TITLE
[Feature] adding shades to `easyclick` and `gridmove` labels

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#165]
This is very subtle, but I believe it has a real visual effect on the user. If you look carefully, the labels of Vimium have a gentle shade below them:
![image](https://user-images.githubusercontent.com/39532610/235672329-94408178-c910-4058-a9dd-9ac16351db70.png)

Adding such shades to the vind labels would go a long way in making them more pleasing to the eye. (Although I am wondering now: can you even create shades? The Vimium appearance is `css` controlled, but vind operates outside the browser and with Windows object ... curious about this...)

Thanks for considering!

**Comment by pit-ray** [comment]
Shading would be very difficult API-wise and would slow performance.
For example, EasyClick decays the color of characters after input, but this is burdensome. (That's why I will simplify it in the next version, like gridmove.)
Therefore, it would not be practical.

Also, in recent years, flat designs are preferred over shaded designs.

As for the visibility of the labels, I would like to take a solution like #114.

Thanks.
