### ISSUE TITLE
[Feature] Detect windows objects ad assign shortcuts to them for user interaction

### ISSUE THREAD

**Issue by pidgeon777** [pit-ray/win-vind#2]
This cool extension is available in Chrome:

https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb

It would be awesome to develop a tool for controlling windows and their objects (TreeView, ListView, Toolbars...) in a similar way of that Chrome extension: once a user triggers a shortcut, a number of labels displaying sequence of characters appear in the front of the dynamic windows objects, and by typing those characters in sequence, then a click/control send/focus is triggered on it according to the target object.

A sample of what I mean:

![image](https://user-images.githubusercontent.com/13739892/101070099-2dd3f280-359b-11eb-8520-155a82a1c4f6.png)

The basic idea would be:

1. Scan all of the windows looking for their controls (buttons, edit boxes, etc.)
2. Draw some boxes near them with the key sequence which would activate them.
3. Wait for the user to type the character sequence related to the desired object to activate.

**Comment by pit-ray** [comment]
I would like to have that feature too.

The current mouse movement methods of win-vind are very poor, so the identifier-based method like Vimium or EasyMotion you suggested is desirable. By the way, the function called `Jump Cursor by Keyboard Mapping` by `f` is implemented as a degraded alternative method of such an identifier-based move method. 

#### About your basic idea
`2` and `3` are able to be implemented algorithmically. However, `1` has some concerns. The GUI objects are implemented by Win32 API, Qt, the vendor's own controls or etc, so we might not be able to know whether some objects are controllable objects by a single API.

##### Some ideas for how to scan
- Scanning via each API. In the minor case, some objects just may not be possible.
- Getting the coordinates with image processing. But, concerned computing costs.

If you have an idea for scanning, please let me know.  

I am currently re-designing the fundamental algorithm or fixing some serious problems. As soon as they are finished, I will consider the specifics.

**Comment by pidgeon777** [comment]
> Getting the coordinates with image processing. But, concerned computing costs.

I also thought about this, could be interesting but probably with a certain computing cost as you said.

**Comment by pit-ray** [comment]
I implemented the feature called `EasyClick` in order to detect GUI objects from your idea.

It currently works good and its speed is also no problem by using some caches. The caches update automatically at every change of target window or resize one. However, the maximum number of drawn labels are only 676. In other words, all objects are detected, but not drawn than 676.

Additionally, The function performs well as long as a target application supported UI Automation. For example, `EasyClick` also detect URL like Vimium on Microsoft Edge, but detects the only UI on Google Chrome or Firefox. Basically, it works on all standard applications of Windows.

I added new bindings.
- EasyClick (`F`)
- UpdateEasyClick (`<C-F>`); manually updating caches.

You can use EasyClick in the latest version from https://github.com/pit-ray/win-vind/tree/master/bin, but it may have some serious problems unrevealed. So, I recommend waiting until the latest stable version.

## Demo
https://user-images.githubusercontent.com/42631247/102794676-0f6d5400-43ef-11eb-99ce-60432113c84d.mp4
