### ISSUE TITLE
[Bug] imap <win-]> <to_gui_normal> inserts ] as well

### ISSUE THREAD

**Issue by edshamis** [pit-ray/win-vind#228]
# About Bug
I defined in .win-vind
imap <win-]> <to_gui_normal>

It works, but at the same time ] is pressed.
For example, while in terminal I press win-], GUI Normal mode is activated but ] is inserted as well 

# Environments
[Windows]
      Edition: Windows 10 Home
      Version: 22H2
Build Numbers: 10.0.19045
 Architecture: x64

[win-vind]
      Version: 5.11.0.0

**Comment by pit-ray** [comment]
This is expected behavior. Insert mode basically executes the command after it is typed so as not to degrade performance. However, as an exception, one key to one key mappings are entered simultaneously, so if you `imap tab <f12>` and `imap <f12> <to_gui_normal>`, the tab will not be entered. Note that the combination key like `<win-]>` will always be entered.
