### ISSUE TITLE
[Question] Can I use win-vind in Linux or MacOS?

### ISSUE THREAD

**Issue by PubCyBerry** [pit-ray/win-vind#27]
**Question**
A clear and concise description of what you have.

Dear pit-ray.

I'm a big fan of your win-vind.
I don't use mouse that much since I found win-vind.
Now I want it to use on Linux(Ubuntu) or MacOS.
Is it Compatible with them? if not, do you have any plan to develop?

**Comment by pit-ray** [comment]
Thank you for using it.

As the name implies, **win-vind** is only supported on Windows. I have tested it with **Wine** in Ubuntu before, but EasyClick did not work.

Cross-platform is technically possible, but I don't plan due to small demands since Linux and MacOS are more CUI oriented and especially Linux support the window manager. There are some other concerns such as financial cost due to I don't have MacOS or the implementation cost there are no contributors for development.

There are alternatives such as **i3wm** and **xdotool** for Linux, and **Karabiner** and **Keyboard Maestro** for MacOS.

Sorry. Thanks.

**Comment by thanhnguyen2187** [comment]
Hi @pit-ray. Thanks for the awesome plugin. Sorry for digging this up, but the killer feature is "hinting" (label some click-able places the key combinations to get them). Are you aware of any Linux/X11 tool that does that?

**Comment by pit-ray** [comment]
@thanhnguyen2187 
For a gridmove (https://github.com/pit-ray/win-vind/discussions/155#discussioncomment-5650643) equivalent of win-vind, there is a project called [warpd](
https://github.com/rvaiya/warpd). For easylick, I don't know of any alternatives in X11, but you may want to refer to Hacker News and Reddit posts about win-vind, as I see that topic frequently.

Thanks.
