### ISSUE TITLE
[Question] Swtiching from Insert to EDI NORMAL without cursor moving to the right

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#42]
When I switch from INSERT to EDI NORMAL (Esc+Right Arrow) the cursor moves to the right. Is this intended? It throws off my writing sequence (in Microsoft Word) and I am wondering if it can be changed that the cursor stays in the same location.

Thanks.

- Windows 10 Edition: Pro
- OS Type: 64bit
- OS Version: 20H2
- OS Build: 19042.1348
- win-vind Version: 4.2.1
- win-vind Type: installer
- Is it reproducible?: Yes

**Comment by pit-ray** [comment]
This is intentional behavior.
In Insert mode, this is caused by the input key being transmitted to Windows. For example, you can redefine it as follows.

Use **Insert -> Editor Normal** with `<capslock>`.
```vim
imap <capslock> <f15>
inoremap <f15> to_edi_normal
```
I know that the default bindings are inconvenient, but I am cautious about updating them for compatibility reasons.
And, if possible, please replace the title of the Issue with an appropriate one.

Thanks.

**Comment by gilbh** [comment]
Thank you. I added the two lines to .vindrc and reloaded the program, but the behavior is the same (even when CAPS LOCK is on). 

I think I am not getting something in your answer. Could you please explain what I am doing wrong?

Thanks,
Gil

**Comment by pit-ray** [comment]
`<Capslock>` only presses CapsLock, not Shift+Capslock. For Shift+CapsLock, use `<shcapslock>`.

Try other keys as well, such as the right alt key.

```vim
inoremap <ralt> to_edi_normal
```

See also this help.
https://pit-ray.github.io/win-vind/faq/#how-do-i-make-a-mode-transition-without-esc

Thanks.

**Comment by gilbh** [comment]
Thanks! I will play around with this some more. Best!
