### ISSUE TITLE
[Question] How can I slow the mouse speed in GN mode?

### ISSUE THREAD

**Issue by ezynox** [pit-ray/win-vind#51]
win-vind 4.2.1
<br/>

In GUI normal mode, my mouse moves super fast. 
One stroke of h,j,k,l leaves half across the screen.

I wrote this in my ~/.win-vind/.vindrc file,

```
set cursor_accel =5
set cursor_maxv = 1
set cursor_tweight = 10
```
but nothing changed.

Am I doing wrong something? Need help!

**Comment by pit-ray** [comment]
win-vind reproduces the physical acceleration motion, so it has a lot of parameters and is difficult to adjust optimally.

Therefore, you have to start with the default values and adjust only the `cursor_accel`. The higher the value makes the faster movement, and the smaller does slower. In command mode, you can adjust it directly, such as `:set cursor_accel=100`, and know the current value with `:set cursor_accel?`.

Then, determine the time units of motion with `cursor_tweight`. The smaller gives the faster movement because the mouse is moved in smaller time units. The larger makes it slower since it is done in rough time intervals.

If you have a better idea with fewer parameters and more natural movement, please post a pull request.

Thanks.
