### ISSUE TITLE
Easy Click FF is really slow[Question]

### ISSUE THREAD

**Issue by MNCODE** [pit-ray/win-vind#9]
**Question**
Is it normal that the Easy Click FF takes long time to load the options?
It is definetly slower than the vimium FX on Firefox. 
I'm using a Windows 10 8GB Ram 4x2,4GHz i5 6300U.

Is it because it is loading the window information from the windows sdk?

**Comment by pit-ray** [comment]
Thank you for using it!

The drawing process is very heavy, so I intentionally give some delay to only drawing to respond to key-input. However, must generally use multi-thread, and divide key-input and drawing. I am implementing it now.

In [v3.2.2](https://github.com/pit-ray/win-vind/releases/tag/v3.2.2), this problem is a little bit solved. Please try it.

**Comment by MNCODE** [comment]
Works fine :) 
It has some strange behaviour when moving the window with the mouse. 
The EasyClick drawings should disappear, when the window moves.

**Comment by pit-ray** [comment]
Thank you for trying it.

Would hinting disappear completely, or just blink?

The process order of EasyClick is  
**Scanning positions of GUI objects** → **Generating Hints** → **Matching with inputs and Drawing hints**  
so if you move the scanned window, the positions of drawn hints and correct positions are different. Therefore, don't move a window after scanning. If you move it, cancel it and re-scan.

Generally, if we move a window, it will re-draw itself. So hinting may disappear temporarily and blink.

**Comment by MNCODE** [comment]
The Hints are staying in there positions and are floating in middle of nowhere.
